{
    "name": "Gestion des Ressources Humaines",
    "version": "1.0",
    "author": "TELIA INFORMATIQUE",
    "depends":["Referentiel_Global","hr","hr_contract"],
    "data":[
        'security/security.xml',
        'security/restricted_company_rule.xml',
        "security/ir.model.access.csv",
        "views/views.xml",
        "views/hr_employee.xml",
        "views/hr_contract.xml",
        "views/menus.xml",
        "data/data.xml",
    ],
    "category": "EPE",
    "Summary": "Gestion des Ressources Humaines",
    "installable": True,
    "auto_install": False,
}
